//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FS22_Mod_Manager {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "17.5.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Documents\\My Games\\FarmingSimulator2022")]
        public string UserDataPath {
            get {
                return ((string)(this["UserDataPath"]));
            }
            set {
                this["UserDataPath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C:\\Program Files (x86)\\Farming Simulator 2022\\FarmingSimulator2022.exe")]
        public string GameExePath {
            get {
                return ((string)(this["GameExePath"]));
            }
            set {
                this["GameExePath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C:\\fs22mods")]
        public string ModFolderPath {
            get {
                return ((string)(this["ModFolderPath"]));
            }
            set {
                this["ModFolderPath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool AllowDoubleClick {
            get {
                return ((bool)(this["AllowDoubleClick"]));
            }
            set {
                this["AllowDoubleClick"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool ModFodlerOverride {
            get {
                return ((bool)(this["ModFodlerOverride"]));
            }
            set {
                this["ModFodlerOverride"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool LaunchWithConsole {
            get {
                return ((bool)(this["LaunchWithConsole"]));
            }
            set {
                this["LaunchWithConsole"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool LaunchWithCheats {
            get {
                return ((bool)(this["LaunchWithCheats"]));
            }
            set {
                this["LaunchWithCheats"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool LaunchAsRestart {
            get {
                return ((bool)(this["LaunchAsRestart"]));
            }
            set {
                this["LaunchAsRestart"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("100, 100")]
        public global::System.Drawing.Point MainWindowLocation {
            get {
                return ((global::System.Drawing.Point)(this["MainWindowLocation"]));
            }
            set {
                this["MainWindowLocation"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool OverwriteOnCopy {
            get {
                return ((bool)(this["OverwriteOnCopy"]));
            }
            set {
                this["OverwriteOnCopy"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Medium")]
        public string performanceClass {
            get {
                return ((string)(this["performanceClass"]));
            }
            set {
                this["performanceClass"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1.000000")]
        public string lodDistanceCoeff {
            get {
                return ((string)(this["lodDistanceCoeff"]));
            }
            set {
                this["lodDistanceCoeff"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1.000000")]
        public string terrainLODDistanceCoeff {
            get {
                return ((string)(this["terrainLODDistanceCoeff"]));
            }
            set {
                this["terrainLODDistanceCoeff"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1.000000")]
        public string foliageViewDistanceCoeff {
            get {
                return ((string)(this["foliageViewDistanceCoeff"]));
            }
            set {
                this["foliageViewDistanceCoeff"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public string maxNumMirrors {
            get {
                return ((string)(this["maxNumMirrors"]));
            }
            set {
                this["maxNumMirrors"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool DeleteToRecycleBin {
            get {
                return ((bool)(this["DeleteToRecycleBin"]));
            }
            set {
                this["DeleteToRecycleBin"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool OnlyShowZipFiles {
            get {
                return ((bool)(this["OnlyShowZipFiles"]));
            }
            set {
                this["OnlyShowZipFiles"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C:\\fs22mods")]
        public string DefaultFavouritesFolder {
            get {
                return ((string)(this["DefaultFavouritesFolder"]));
            }
            set {
                this["DefaultFavouritesFolder"] = value;
            }
        }
    }
}
